// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_amateur = "CgkI6qTC79QOEAIQAQ"; // <GPGSID>
        public const string achievement_novice = "CgkI6qTC79QOEAIQAA"; // <GPGSID>
        public const string achievement_officier = "CgkI6qTC79QOEAIQBQ"; // <GPGSID>
        public const string achievement_lieutenant = "CgkI6qTC79QOEAIQBg"; // <GPGSID>
        public const string achievement_dtective = "CgkI6qTC79QOEAIQCQ"; // <GPGSID>
        public const string achievement_trouble_fte = "CgkI6qTC79QOEAIQCw"; // <GPGSID>
        public const string achievement_fin_limier = "CgkI6qTC79QOEAIQCA"; // <GPGSID>
        public const string achievement_stagiaire = "CgkI6qTC79QOEAIQBA"; // <GPGSID>
        public const string achievement_slowrunner = "CgkI6qTC79QOEAIQDA"; // <GPGSID>
        public const string achievement_capitaine = "CgkI6qTC79QOEAIQBw"; // <GPGSID>
        public const string achievement_expert = "CgkI6qTC79QOEAIQAw"; // <GPGSID>
        public const string achievement_confirm = "CgkI6qTC79QOEAIQAg"; // <GPGSID>
        public const string achievement_speedrunner = "CgkI6qTC79QOEAIQCg"; // <GPGSID>

}

